### ISSUE TITLE
Support db:structure:dump and db:structure:load

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/activerecord-cockroachdb-adapter#2]
The Postgres DatabaseTasks implementation uses `pg_dump` to dump the database in `db:structure:dump`. CockroachDB doesn't support `pg_dump`, so this plugin should use `DUMP` and its inverse when they're officially supported.

**Comment by yob** [comment]
This would be super helpful.

I've been experimenting with cockroachdb on an existing rails 6.1 app which uses `config.active_record.schema_format = :sql`. I added cockroachdb as a secondary database using the new rails 6.1 multi-database support:

```yaml
development:
  primary:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
  secondary:
    adapter: cockroachdb
    url: <%= ENV['SECONDARY_DATABASE_URL'] %>
    migrations_paths: db/secondary_migrate
```

Sadly, `config.active_record.schema_format` is a global setting shared by all database connections. This adapter only supports `:ruby` so it'd be nice if I can use that, but our large existing database is complex enough that it can't be saved as a `:ruby` schema. It only works as an `:sql` schema. I'm at a stalemate :shrug:
