### ISSUE TITLE
Rails 7 version throws "PG::UndefinedObject"

### ISSUE THREAD

**Issue by aemadrid-twx** [cockroachdb/activerecord-cockroachdb-adapter#257]
```shell
❯ bundle show activerecord-cockroachdb-adapter
/Users/some_user/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-cockroachdb-adapter-7.0.0

❯ bundle show rails
/Users/some_user/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rails-7.0.3.1

❯ ruby -v
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]

❯  be rake db:create
Created database 'some_app_development'
PG::UndefinedObject: ERROR:  unrecognized configuration parameter "crdb_version"
Couldn't create 'some_app_development' database. Please check your configuration.
rake aborted!
ActiveRecord::ConnectionNotEstablished: PG::UndefinedObject: ERROR:  unrecognized configuration parameter "crdb_version"
/Users/some_user/.asdf/installs/ruby/3.1.1/bin/bundle:25:in `load'
/Users/some_user/.asdf/installs/ruby/3.1.1/bin/bundle:25:in `<main>'
```

**Comment by rafiss** [comment]
Could you share your CockroachDB version and your rails database configuration (or URL) you used to connect?

**Comment by aemadrid-twx** [comment]
Cockroach V22.1.4

```yaml
default: &default
  adapter: cockroachdb
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: some_app_development
  host: localhost
  port: 26527
  user: root
  password: ""
  sslmode: disable
```
